= Kafka Connect JDBC test environment

This Docker Compose can be used to spin up an environment in which to explore and test the Kafka Connect JDBC source connector. 

The associated blog article can be found at https://www.confluent.io/blog/kafka-connect-deep-dive-jdbc-source-connector

.Current environment

|=====================================================================
|Confluent Platform | 5.1.0
|MySQL              | 8.0.13
|Postgres           | 11.1
|MS SQL Server      | 2017 (RTM-CU13) (KB4466404) - 14.0.3048.4 (X64)
|Oracle             | 12.2.0.1.0
|=====================================================================

== Getting a CLI session

* KSQL
+
[source,bash]
----
docker-compose exec ksql-cli ksql http://ksql-server:8088
ksql> LIST TOPICS;
ksql> PRINT 'docker-connect-offsets' FROM BEGINNING;
ksql> CREATE STREAM ACCOUNTS WITH (KAFKA_TOPIC='mysql-06X-accounts', VALUE_FORMAT='AVRO');
ksql> SELECT ROWKEY, ID, FIRST_NAME + ' ' + LAST_NAME FROM ACCOUNTS;
----

* MySQL
+
[source,bash]
----
To connect to the DB:
docker-compose exec mysql bash -c 'mysql -u root -p$MYSQL_ROOT_PASSWORD'
 or
docker exec -it bxxxx bash  --user=root --password=$MYSQL_ROOT_PASSWORD
mysql>ALTER USER 'root' IDENTIFIED WITH mysql_native_password BY '123';
mysql>exit
----

* Postgres
+
[source,bash]
----
docker-compose exec postgres bash -c 'psql -U $POSTGRES_USER $POSTGRES_DB'
----

* Oracle
+
[source,bash]
----
docker-compose exec oracle bash -c 'sqlplus sys/$ORACLE_PWD@localhost:1521/ORCLCDB as sysdba'
----

* MS SQL Server
+
[source,bash]
----
docker-compose exec mssql bash -c '/opt/mssql-tools/bin/sqlcmd -l 30 -S localhost -U sa -P $SA_PASSWORD'
----


== Example Connector Configuration

* MySQL-add connector with a post
** GET /connectors – returns a list with all connectors in use
** GET /connectors/{name} – returns details about a specific connector
** POST /connectors – creates a new connector; the request body should be a JSON object containing a string name field and an object config field with the connector configuration parameters
+
[source,bash]
----
curl -X POST http://localhost:8083/connectors -H "Content-Type: application/json" -d '{
        "name": "jdbc_source_mysql_01",
        "config": {
                "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
                "connection.url": "jdbc:mysql://mysql:3306/demo",
                "connection.user": "connect_user",
                "connection.password": "asgard",
                "topic.prefix": "mysql-01-",
                "mode":"bulk",
                "poll.interval.ms" : 3600000
                }
        }'

 response:
        {"name":"jdbc_source_mysql_01","config":{"connector.class":"io.confluent.connect.jdbc.JdbcSourceConnector","connection.url":"jdbc:mysql://mysql:3306/demo","connection.user":"connect_user","connection.password":"asgard","topic.prefix":"mysql-01-","mode":"bulk","poll.interval.ms":"3600000","name":"jdbc_source_mysql_01"},"tasks":[],"type":null}
curl -X GET http://localhost:8083/connectors/
curl -X GET http://localhost:8083/connectors/jdbc_source_mysql_01
ksql> PRINT 'docker-connect-offsets' FROM BEGINNING;
u will see the content of db in the topics
insert to db
INSERT INTO `demo`.`accounts` VALUES (21, 'lolik', 'samuel', 'loliksamuel', 'xxx', '2019-03-03', '2019-03-03 09:09:09');
after an hour u will see it in the topic
----

* Postgres
+
[source,bash]
----
curl -X POST http://localhost:8083/connectors -H "Content-Type: application/json" -d '{
        "name": "jdbc_source_postgres_01",
        "config": {
                "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
                  "connection.url": "jdbc:postgresql://postgres:5432/postgres",
                "connection.user": "connect_user",
                "connection.password": "asgard",
                "topic.prefix": "postgres-01-",
                "mode":"bulk",
                "poll.interval.ms" : 3600000
                }
        }'
----

* Oracle
+
[source,bash]
----
curl -X POST http://localhost:8083/connectors -H "Content-Type: application/json" -d '{
                "name": "jdbc_source_oracle_01",
                "config": {
                        "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
                        "connection.url": "jdbc:oracle:thin:@oracle:1521/ORCLPDB1",
                        "connection.user": "connect_user",
                        "connection.password": "asgard",
                        "topic.prefix": "oracle-01-",
                        "table.whitelist" : "NUM_TEST",
                        "mode":"bulk",
                        "poll.interval.ms" : 3600000
                        }
                }'
----

* MS SQL Server
+
[source,bash]
----
curl -X POST http://localhost:8083/connectors -H "Content-Type: application/json" -d '{
                "name": "jdbc_source_mssql_01",
                "config": {
                        "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
                        "connection.url": "jdbc:sqlserver://mssql:1433;databaseName=demo",
                        "connection.user": "connect_user",
                        "connection.password": "Asgard123",
                        "topic.prefix": "mssql-01-",
                        "table.whitelist" : "demo..num_test",
                        "mode":"bulk",
                        "poll.interval.ms" : 3600000
                        }
                }'
----
